--* criando por objeto

CREATE OR REPLACE TYPE OBJ_PRODUTO AS OBJECT(
    ID INTEGER, 
    CATEGORIA VARCHAR2(1), 
    NOME VARCHAR2(20),
    PRECO FLOAT
);


CREATE  TABLE TB_PRODUTOS OF OBJ_PRODUTO;
ALTER TABLE TB_PRODUTOS MODIFY(id NOT NULL);

ALTER TABLE TB_PRODUTOS ADD CONSTRAINT ID PRIMARY KEY(ID);


DROP TABLE TB_PRODUTOS 

--* CRIANDO COM SQL PURO
CREATE TABLE TABELA_PRODUTOS (
    ID INTEGER NOT NULL, 
    CATEGORIA VARCHAR2(1), 
    NOME VARCHAR2(20),
    PREÇO FLOAT,
    PRIMARY KEY(ID)
);


--* INSERT PRODUTOS 

CREATE OR REPLACE TYPE V_CATEGORIA AS VARRAY(10) OF VARCHAR2(1);
CREATE OR REPLACE TYPE V_NOMEPROD AS VARRAY(10) OF VARCHAR2(20);
CREATE OR REPLACE TYPE V_PRECO AS VARRAY(10) OF FLOAT;

DECLARE 
    CATEGORIAPRODUTO V_CATEGORIA := V_CATEGORIA('A','A','A','B','B','B','L','L','L','L');
    NOMEPRODUTO V_NOMEPROD := V_NOMEPROD('ARROZ','FEIJÃO','MACARRÃO','LEITE','REFRIGERANTE','SUCO','DETERGENTE','AMACIANTE','ÁLCOOL','SABÃO EM PÓ') ;
    PRECOPRODUTO V_PRECO := V_PRECO(15.50,5.30,4.75,5.5,6,3,2.75,16.45,6.45,10.95);
BEGIN
    FOR I IN 1..10 LOOP
        INSERT INTO TB_PRODUTOS VALUES(I,CATEGORIAPRODUTO(I),NOMEPRODUTO(I),PRECOPRODUTO(I));
    END LOOP;
END ;






SELECT * FROM TB_PRODUTOS;

--* CRIAR FUNCTION

CREATE OR REPLACE FUNCTION FUNC_REAJUSTAPRECO (
    P_CODIGOPRODUTO IN INTEGER,
    P_PORCENTAUMENTO IN FLOAT
) RETURN VARCHAR2 IS
    RESPOSTA VARCHAR2(60);
    VALOR_AJUSTADO TB_PRODUTOS.PRECO%TYPE;
    VALOR_PRECO TB_PRODUTOS.PRECO%TYPE;
BEGIN

    SELECT PRECO INTO VALOR_PRECO FROM TB_PRODUTOS WHERE ID = P_CODIGOPRODUTO;

    IF P_PORCENTAUMENTO > 50 OR P_PORCENTAUMENTO < 0  THEN 
        RESPOSTA := 'Percentual fora da faixa de valor permitido';
        RETURN RESPOSTA ;
    ELSE 
        VALOR_AJUSTADO := VALOR_PRECO + (VALOR_PRECO * (P_PORCENTAUMENTO / 100));
        UPDATE TB_PRODUTOS SET PRECO = VALOR_AJUSTADO  WHERE PRECO = VALOR_PRECO;
        RESPOSTA :='Alteração realizada com sucesso';
        RETURN RESPOSTA ;

    END IF ;

    EXCEPTION
        WHEN no_data_found THEN 
            RESPOSTA := 'Código não encontrado'; 
            RETURN RESPOSTA;

END FUNC_REAJUSTAPRECO;
/


SELECT PRECO FROM TB_PRODUTOS WHERE TB_PRODUTOS.ID=8;

BEGIN
    DBMS_OUTPUT.PUT_LINE(FUNC_REAJUSTAPRECO(8,65));
END;
SELECT PRECO FROM TB_PRODUTOS WHERE TB_PRODUTOS.ID=8;
    








