--* PROCEDURE FABRIC
--* PSEUDO-PROCEDURE FABRIC 
CREATE OR REPLACE TYPE ATRIBUTOS AS VARRAY(2) OF VARCHAR2(10);
CREATE OR REPLACE PROCEDURE PROCFABRIC (
  NOMETYPE VARCHAR2,
  NOMEATRIBUTOS ATRIBUTOS) IS
  
BEGIN
    EXECUTE IMMEDIATE'GRANT CREATE OR REPLACE TYPE '||NOMETYPE||' AS OBJECT(
        '||NOMEATRIBUTOS(1)||' VARCHAR2,
        '||NOMEATRIBUTOS(2)||' INTEGER
    )NOT FINAL;';

END;
--! SUBIR OS PRIVILEGIOS PARA EXECUTAR O COMANDO 
BEGIN
    PROCFABRIC('AVIAO',ATRIBUTOS('MODELO','SERIE'));
END;
